### ISSUE TITLE
JPEG decode fail on the attached image

### ISSUE THREAD

**Issue by ultraembedded** [aquaxis/aq_axis_djpeg#2]
![image-001](https://user-images.githubusercontent.com/7809581/93136362-b39a7d00-f6d3-11ea-8992-d722ce10de6f.jpg)

The attached image fails to decode with your JPEG decoder core for some unknown reason.
This is unexpected as other images generated with exactly the same image tools are ok.

Any ideas? @nekomona

**Comment by ultraembedded** [comment]
![corrupted_output](https://user-images.githubusercontent.com/7809581/93137039-c9f50880-f6d4-11ea-9014-4be66e63376b.jpg)

Here is the corrupted output generated by the JPEG decoder.

**Comment by nekomona** [comment]
I have pushed that image through the testbench and it gave a positive result, so I believe the image I get from this page might have been recompressed when uploading to GitHub. It might be helpful if that image could be zipped so the image won't get recompressed when uploading.

For the issue itself, I have seen similar outcomes when decoding JPEG generated by `SYSTEMAX JFIF Encoder Ver.2.0.`, which could be related to the behavior of DRI and reset markers.  So if that image does contain DRI header and reset markers, it might be the case. I'm still debugging on that issue, but I'm still trapped in oversized waveforms yet. XP

**Comment by ultraembedded** [comment]
[image-003.jpg.zip](https://github.com/aquaxis/aq_axis_djpeg/files/5252039/image-003.jpg.zip)
Ah! Zip file attached.
The only thing I am surprised by that the same tool (ImageMagic) has produced 1000's of other working JPEG images.

I've built a JPEG based video player on FPGA using this core. It is a really good way of testing 1000's of JPEG images, being as you get to see 25 of them a second ;-)

**Comment by ultraembedded** [comment]
Here is my project - if you are interested;
https://github.com/ultraembedded/FPGAmp

**Comment by nekomona** [comment]
Finally! It turns out to be a bug in the bit-shifter when removing "0xFF00" stuffings on the very first word. When the image data starts with exactly 40 bits inside the shift register and begins with 0xFF 0x00, the 0x00 will be leaked to Huffman decoder before being removed in the following clock and dumping errors onto the following steps.

Onto the image above, the zipped one has exactly the bug condition, but the Huffman code to be matched is coincidentally also 0xFF, which limits the error to only a DC data word in the Y channel. Sadly, differential coding spreads that error to the data output of all following blocks without leaving error traces on decoder inputs. The recompressed one has a different length of headers thus avoided that bug like all other images.

And even more sadly, the [bugfix here](https://github.com/nekomona/aq_axis_djpeg/commit/5b44a01dbe38f0a1f1818a6eba3848f227b824c7) seems to be just adding another AND condition, waiting for a cycle for the shifter to read the following data and remove that 0x00 while shifting into higher bits ......

**Comment by ultraembedded** [comment]
Nice. I ended up writing my own JPEG decoder IP in the meantime anyway :-)

https://github.com/ultraembedded/core_jpeg

**Comment by aquaxis** [comment]
Hello,
Sorry I left it unnoticed for 3 years.
